# Generated by Django 4.2.7 on 2024-01-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsmodel',
            name='Prficiency_levels',
            field=models.CharField(choices=[('★', 1), ('★★', 2), ('★★★', 3), ('★★★★', 4), ('★★★★★', 5), ('★★★★★★', 6), ('★★★★★★★', 7)], max_length=50),
        ),
    ]
