# Generated by Django 4.2.7 on 2024-01-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0002_alter_skillsmodel_prficiency_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skillsmodel',
            name='project_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
