# Generated by Django 4.2.7 on 2024-01-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_profile_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='user',
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='profile_image',
            field=models.ImageField(upload_to='media/images/profile'),
        ),
    ]
