# Generated by Django 4.2.7 on 2024-01-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profileimage_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='profile_image',
            field=models.ImageField(upload_to='user/media/images/profile/'),
        ),
    ]
