# Generated by Django 4.2.7 on 2024-01-17 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_ShowCase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='project_ShowCase.projectdetailsmodel'),
        ),
    ]
